---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 30s
  path: ./cluster
  prune: true
  sourceRef:
    kind: Bucket
    name: flux-system
