apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: weave-gitops-app
spec:
  releaseName: weave-gitops-app
  chart:
    spec:
      chart: weave-gitops
      sourceRef:
        kind: HelmRepository
        name: weave
      version: "2.0.8"
  interval: 30s
  install:
    remediation:
      retries: 3
  values:
    adminUser:
      create: true
      username: admin
      # password is... 'password'
      passwordHash: '$2y$10$If3hNEXnLMdkHo7L/PijguisTcVkNZNdcqDeumEUuAIeGmL.zrGYO'
