apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: dex
  namespace: dex
spec:
  targetNamespace: dex
  interval: 5m
  chart:
    spec:
      chart: dex
      version: 0.6.5
      sourceRef:
        kind: HelmRepository
        name: dex
        namespace: flux-system
      interval: 1m
  values:
    image:
      tag: v2.31.0
    ingress:
      enabled: false
    config:
      # see https://github.com/dexidp/dex/blob/master/config.yaml.dist for config details
      storage:
        type: memory

      web:
        http: 0.0.0.0:5556

      enablePasswordDB: true
      # These lists are filled by generate.py
      staticPasswords: []
      staticClients: []
