apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: dex
  namespace: dex
spec:
  targetNamespace: dex
  interval: 5m
  chart:
    spec:
      chart: dex
      version: 0.6.5
      sourceRef:
        kind: HelmRepository
        name: dex
        namespace: flux-system
      interval: 1m
  values:
    image:
      tag: v2.31.0
    config:
      # Set it to a valid URL
      issuer: http://dex-dex.dex.svc.cluster.local:5556
      # issuer: http://127.0.0.1:5556

      # See https://dexidp.io/docs/storage/ for more options
      storage:
        type: memory

      web:
        http: 0.0.0.0:5556

      staticClients:
      - name: 'Weave GitOps Core'
        id: weave-gitops
        secret: AiAImuXKhoI5ApvKWF988txjZ+6rG3S7o6X5En
        redirectURIs:
        # port has to match browser host?
        - 'http://localhost:9001/oauth2/callback'
        - 'http://0.0.0.0:9001/oauth2/callback'

      # We're going to set up dex to do basic auth rather than use connectors
      enablePasswordDB: true
      staticPasswords:
      - email: "test-user@test.invalid"
        username: "test"
        userID: "08a8684b-db88-4b73-90a9-3cd1661f5466"
        hash: "$2y$10$U3n7E2V2FJA5wpv6o3pFe.EsKo6JbwzasikAKCSn2GEB5hy9JtbYS" #  echo password | htpasswd -BinC 10 admin | cut -d: -f2

      logger:
        level: "debug"
        format: "json"

    ingress:
      enabled: false
      # className: nginx
      # annotations:
      #   cert-manager.io/cluster-issuer: letsencrypt-prod
      # hosts:
      #   - host: dex.dev.example.tld
      #     paths:
      #     - path: /
      #       pathType: ImplementationSpecific
      # tls:
      #   - hosts:
      #     - dex.dev.example.tld
      #     secretName: dex-dev-example-tld
