apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: podinfo-kustomization-0
  namespace: flux-system
spec:
  interval: 30s
  path: ./many-podinfo-kustomizations/podinfo-kustomization-0
  prune: true
  sourceRef:
    kind: Bucket
    name: scenarios
  validation: client
