apiVersion: apps/v1
kind: Deployment
metadata:
  name: podinfo-2
  namespace: many-podinfo-kustomizations
spec:
  replicas: 1
  selector:
    matchLabels:
      app: podinfo-2
  template:
    metadata:
      labels:
        app: podinfo-2
    spec:
      containers:
      - command:
        - ./podinfo
        - --port=8002
        image: ghcr.io/stefanprodan/podinfo:6.1.6
        imagePullPolicy: IfNotPresent
        name: podinfo-2
        ports:
        - containerPort: 8002
          name: http
          protocol: TCP
