apiVersion: v1
kind: Namespace
metadata:
  annotations:
    namespace_id: --
    namespace_root: many-podinfo-kustomizations
    scenario: many-podinfo-kustomizations
  name: many-podinfo-kustomizations
