---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  interval: 30s
  dependsOn:
    - name: infrastructure
  sourceRef:
    kind: Bucket
    name: flux-system
  path: ./apps
  prune: true
  validation: client
